median_filter:
	icpc -Wfatal-errors -std=c++11 -qopenmp median_filter_omp.cpp -o median_filter_omp -I/net/software/local/opencv/3.2.0/include -L/net/software/local/opencv/3.2.0/lib -lopencv_core -lopencv_imgcodecs
